### ISSUE TITLE
Support rendering ORIGCURRENCY section in statement line

### ISSUE THREAD

**Issue by zeldigas** [kedder/ofxstatement#113]
OFX standard supports for statement line to provide information about original currency: it's iso code and conversion rate. See https://www.ofx.org/downloads/OFX%202.2.pdf, page 106 (110 in pdf numbering) for details.

Would be great for ofxstatment to provide support for this element so that plugins can implement this, if source files support this kind of information

**Comment by kedder** [comment]
This makes sense, shouldn't be difficult to add respective fields. Thanks for pointers.

**Comment by zeldigas** [comment]
Do you need help with it? I don't want to commit for fast PR, but probably can do contribution withing 2-3 weeks

**Comment by kedder** [comment]
I'll try to do that this evening, shouldn't be a big deal (famous last words).

**Comment by kedder** [comment]
@zeldigas, does #114 look good to you? Is that what you expect?

**Comment by zeldigas** [comment]
Yep, looks good. As an extra - would be nice to have updated docs for plugin authors if you have such. Especially some tip about backward compatible plugin implementation that can work with both versions < 0.7.2 and >=0.7.2 and add currency info conditionally.

**Comment by kedder** [comment]
AFAICT, that change is backwards compatible. If plugin does not provide the currency, it will simply not appear in the generated OFX.

**Comment by zeldigas** [comment]
I understand, but I mean reverse case - as a plugin author I'd like to support this new feature when assembling statement line but at the same time be backward compatible with older ofxstatement versions. I understand that it will be achievable with some try/except block that checks for new class presence, just thought that if you have some plugin dev guide it's worth adding sample there.

**Comment by kedder** [comment]
Ah, I see what you mean - good point. Unfortunately there is no docs of this kind exist besides the README of [ofxstatement-sample](https://github.com/kedder/ofxstatement-sample), but at least remark in the comments for these attributes would help a bit. Proibably we need to grow more formal docs at some point.

**Comment by kedder** [comment]
@zeldigas do you want a new release?

**Comment by zeldigas** [comment]
No rush for me. I feel that I'll be able to play with this new feature only on this weekend, not earlier
