### ISSUE TITLE
Equabank (CZ) support

### ISSUE THREAD

**Issue by kosciCZ** [kedder/ofxstatement#167]
Hey, I found ofxstatement pretty handy, I used some of the user submitted plugins, which worked great, but there was an option missing for one of my banks. Hence, I'd like to submit it for consideration to be added in the pluggin section. Here's the repository [kosciCZ/ofxstatement-equabankcz](https://github.com/kosciCZ/ofxstatement-equabankcz).

Let me know if you're okay with this, and I'll submit a PR.

**Comment by kedder** [comment]
Hi @kosciCZ, thanks, every plugin is welcomed! Feel free to submit a PR for README with the link to it!
