### ISSUE TITLE
Broken Plugins linkage

### ISSUE THREAD

**Issue by jaik03** [kedder/ofxstatement#258]
I think #256 may have broken linking in plugins. It'll build and operate just fine without a plugin, but I'm getting an "ModuleNotFoundError: No module named 'ofxstatement.tool'" after loading my own plugin, or any other. I think it's tied to trying to deprecate use of pkg_resources and it's breaking the linkage to how plugins should be loaded moving forward.

I'll look at trying to develop a holistic PR, but I'm learning Python as I go so it might be a bit.

**Comment by kedder** [comment]
Yeah, I was afraid of this. I'll look at it this evening.

**Comment by kedder** [comment]
@jaik03 how do you get this error? Tried installing it to the brand new virtualenv and it works for me:

```sh
$ python3 -mvenv ve
$ . ve/bin/activate
$ pip install ~/projects/ofxstatement/ofxstatement
$ pip install ~/projects/ofxstatement/ofxstatement-lithuanian/
$ ofxstatement list-plugins
The following plugins are available: 

  danske           Lithuanian Danske bank CSV
  litas-esis       Standard Lithuanian LITAS-ESIS format
  swedbank         Lithuanian Swedbank CSV

```

**Comment by jaik03** [comment]
I was doing it via pipenv. I'm using a Mac with python 3.11 via Homebrew. Give me a day or two and I'll spin up a linux instance to try and replicate and post the output here.

**Comment by jaik03** [comment]
When I do it in a fresh linux environment as above, I get similar results as you. I'll chalk it up to something funky with my development environment. I can't install venv on my mac at the moment to try it that way to see what happens when I do it that way. If I figure it out I'll post it here for posterity.
