### ISSUE TITLE
<BANKID /><ACCTID /> remain blank

### ISSUE THREAD

**Issue by jomajojo** [kedder/ofxstatement#314]
I am using n26 plugin.
my config.ini is :
[n26]
plugin = n26
currency = EUR
bank_id = N26 Bank
account = DE12345678910

after generating the ofx file the  statements BANKID and ACCTID are like in the title , blank

**Comment by kedder** [comment]
Hi @jomajojo , I suggest you to reach out to N26 plugin maintainers (https://github.com/3v1n0/ofxstatement-n26). Bank id and account id is the data that plugin needs to provide to ofxstatement.
