### ISSUE TITLE
Proposal to Add New Plugins for ofxstatement: ofxstatement-be-hellobank-fr and ofxstatement-be-vdk-fr

### ISSUE THREAD

**Issue by Jibuus** [kedder/ofxstatement#319]
Hello,

I have developed two plugins for ofxstatement to support the bank statement formats of two institutions in Belgium. I would like to propose their addition to the GitHub page that lists community plugins.

### Proposed Plugins:
1. **ofxstatement-be-hellobank-fr**  
   - **Functionality**: This plugin allows processing of account statements provided by Hello Bank in Belgium.
   - **Plugin Link**: [https://github.com/Jibuus/ofxstatement-be-hellobank-fr](https://github.com/Jibuus/ofxstatement-be-hellobank-fr)

2. **ofxstatement-be-vdk-fr**  
   - **Functionality**: This plugin is designed for handling account statements from VDK Bank in Belgium.
   - **Plugin Link**: [https://github.com/Jibuus/ofxstatement-be-vdk-fr](https://github.com/Jibuus/ofxstatement-be-vdk-fr)

I would appreciate any feedback and am happy to discuss further steps for adding these plugins. If modifications or adjustments are required, I am available to make them.

Thank you very much for your work on ofxstatement and for considering this proposal!

Best regards,  
Jibuus

**Comment by kedder** [comment]
Hi @Jibuus thanks! Feel free to change [README.rst](/kedder/ofxstatement/edit/master/README.rst) and submit a PR. I'll happily merge it.

**Comment by Jibuus** [comment]
Hi @kedder,  done! The PR has been submitted. Thank you!
