### ISSUE TITLE
ofxstatement-czech lost

### ISSUE THREAD

**Issue by msusta** [kedder/ofxstatement#44]
It seems that @mcepl deleted the repository with ofxstatement-czech. I guess you can remove the reference to it from README.MD.
Not sure what was the original motivation behind that. I've searched for sources and I found https://pypi.python.org/pypi/ofxstatement-czech.

**Comment by mcepl** [comment]
Just moved repository to https://gitlab.com/mcepl/ofxstatement-czech, nothing else.

**Comment by kedder** [comment]
@msusta, thanks for spotting, @mcepl thanks for the patch!
