### ISSUE TITLE
Mention Debian/Ubuntu packages

### ISSUE THREAD

**Issue by gerasiov** [kedder/ofxstatement#58]
Please mention in README, that in Debian and Ubuntu distributions one can install ofxstatement from official repositories. Packages are named ofxstatement and ofxstatement-plugins:

https://packages.debian.org/search?keywords=ofxstatement
https://packages.debian.org/search?keywords=ofxstatement-plugins

http://packages.ubuntu.com/search?keywords=ofxstatement

**Comment by kedder** [comment]
Wow, this is awesome! Thank you!
