### ISSUE TITLE
Re-license?

### ISSUE THREAD

**Issue by motin** [kedder/ofxstatement#74]
Heyo! :)

I am a long-time open source contributor and promoter, and this project looks like a good base to to some substantial contributions on top of, but the use of GPL is making it impossible for me to use or contribute to the development of ofxstatement since not only do I do open source, I also sell my time as a programmer for other companies, and in those projects GPL is not an option. 

Will you consider re-licensing this to LGPL, MIT or BSD, http://unlicense.org/ or similar?

**Comment by gerasiov** [comment]
1. I should notice, that all 16 contributors should agree to license change.

2. I also work in proprietary projects and see no problems with this. Let's be honest, you mean "I want to sell ofxstatement as (part) of my proprietary software, please let me do this"?

**Comment by motin** [comment]
1. Yes, we could tag them in this thread. Not sure what to do if someone does not answer/vote though - do you know proper procedure?
2. That'd be cool, but I have no proprietary software where I want to sell ofxstatement as part of. My  motives are rather:

* I want to include ofxstatement as (part) of my clients' proprietary softwares rather than developing similar code from scratch or use an inferior library/solution
* I want to be able to work with and contribute to ofxstatement (and similar projects) while being paid by my clients
* I want others in my position to be able to work with and contribute to ofxstatement (and similar projects) while being paid by their clients

Check my github history, I routinely contribute to open-source projects as part of my work as a contractor since it is better for the eco-system and for the clients. A win-win situation :)

Is there any negative effects of re-licensing to a more permissive license?

**Comment by gerasiov** [comment]
>do you know proper procedure?

Only clean room re-implementation.

>I want to include ofxstatement as (part) of my clients' proprietary softwares rather than developing similar code from scratch or use an inferior library/solution

You could do this following the simple rules:
* Use GPL licensed ofxstatement as separate binary.
* Claiming you use oxfstatement in your software package.
* Providing (e.g. by request) sources of ofxstatement under GPL you use to anyone who legally receive your software package.
(s/you/your customer/g)

> I want to be able to work with and contribute to ofxstatement (and similar projects) while being paid by my clients
>I want others in my position to be able to work with and contribute to ofxstatement (and similar projects) while being paid by their clients

GPL does not restrict this while you follow the requirements.

**Comment by gerasiov** [comment]
> Check my github history, I routinely contribute to open-source projects as part of my work as a contractor since it is better for the eco-system and for the clients. A win-win situation :)

I'm sorry if my comment was a little bit offensive. I just wanted to say that the only negative effect of GPL for you is inability to use it as a library. All other "problems" do not exist.

**Comment by motin** [comment]
Thanks for a well-written and informative reply :)

> * Claiming you use oxfstatement in your software package.
> * Providing (e.g. by request) sources of ofxstatement under GPL you use to anyone who legally receive your software package.
> (s/you/your customer/g)

This is no problem at all, since we already do this with MIT/BSD-licensed code (we always publish forks and create PRs where appropriate).

> * Use GPL licensed ofxstatement as separate binary.

This is where the real problem lies. While it is true in theory, it is still [up to legal interpretation whether or not](https://opensource.stackexchange.com/a/2939) [the client's software's interaction with the binary constitutes ](https://softwareengineering.stackexchange.com/a/110401) (eg "But if the semantics of the communication are intimate enough, exchanging complex internal data structures, that too could be a basis to consider the two parts as combined into a larger program."), and the problem lies not within finding a possibly technically/legally valid solution, but within convincing their legal department to accept using and contributing to GPL-licensed code as part of paid contractor work. 

Talking from experience, I have yet to find a client that allows this, and most contractor agreements specifically require us to warrant that no third party licenses may expose the company to lawsuits, or else we may be deemed personally responsible. 

All in all, I believe you would get more contributions and real-world adoption by re-licensing than not. To understand both sides of this, do you know if there are any negative effects of re-licensing to a more permissive license, granted that it would be feasible?

**Comment by kedder** [comment]
@motin, I can certainly agree that some organizations explicitly prohibit GPL (and other copyleft) software to be used by their own software. Because of uncertainty and doubt or "just in case", even though GPL imposes no restrictions on _using_ the software. That is understandable, but it is also very clear that if organization wants this kind of "insurance", it has to pay for reimplementation of already existing software under its own terms.

I wrote ofxstatement to scratch my own itch and shared it in case someone else would find it useful too. I still use it every month and it has been a huge time saver for me. In case someone else would want to take it on the next level and make something awesome using my work, I'm all for it, but I'd like to be able to use that software too. I think I have that right. For this purpose GPL works pretty well IMO.

I can see the argument that no-one will want to do anything awesome with it _because_ the license is too restrictive. This may be true or false, but in the worst case, I still have a tool that I can use.

That said, I'm pretty happy with current licensing. I don't think GPLv3 is a right choice for all software, but it is pretty well balanced for ofxstatement.

**Comment by motin** [comment]
> I wrote ofxstatement to scratch my own itch and shared it in case someone else would find it useful too. I still use it every month and it has been a huge time saver for me. In case someone else would want to take it on the next level and make something awesome using my work, I'm all for it, but I'd like to be able to use that software too. I think I have that right. For this purpose GPL works pretty well IMO.

MIT/BSD: "shared it in case someone else would find it useful too"
GPL: "shared it in case someone else would find it useful too" + "be able to freely use all other software that builds upon it"

I have been around long enough to see so many people reason like this and never get anything out of it due to the GPL restrictions. There is even LGPL if you at least would be willing to allow for other people to scratch their own inches and requiring them to contribute back all changes to ofxstatement (without requiring them to relicense their whole product, of which ofxstatement would be but a small piece if it would be truly amazing). 

Hope ofxstatement is an exception and that you will get that community feedback and improvements and access to new software that you are looking for. 

> I can see the argument that no-one will want to do anything awesome with it because the license is too restrictive. This may be true or false, but in the worst case, I still have a tool that I can use.

Without any data about "others", and even without the argument about it being more likely to get paid contributions back from freelancers and larger companies, we can still see here that a single person (me) has wanted to improve upon your efforts but now am unwilling to do so (relicensing my whole other product to use a single library is out of the question I am afraid).

In the end, yes, you will still have a tool that you can use, but maybe it is also important that others can use it too?

> That said, I'm pretty happy with current licensing. I don't think GPLv3 is a right choice for all software, but it is pretty well balanced for ofxstatement.

For anyone looking for an alternative approach, I found https://github.com/bank2ynab/bank2ynab as a good starting point for future contributions and win-win in the long term.
