### ISSUE TITLE
pip3 install ofxstatement-be-kbc not founding a matching distribution

### ISSUE THREAD

**Issue by kjellmoens** [kedder/ofxstatement#77]
Hi, 

Can you help me ?

I get this error :   Could not find a version that satisfies the requirement ofxstatement-be-kbc (from versions: )
No matching distribution found for ofxstatement-be-kbc

Thanks

**Comment by kedder** [comment]
Hi, sorry for untimely response, but the problem is likely to be solved now - the `ofxstatement-be-kbc` was released on pypi https://pypi.org/project/ofxstatement-be-kbc
