### ISSUE TITLE
ING Belgium plugin updated

### ISSUE THREAD

**Issue by jbbandos** [kedder/ofxstatement#81]
Hello,
I've taken the plugin changes by Theo Marescaux, fixed them and have a working plugin to convert ING Belgium CSV files to OFX. It is in my repo https://github.com/jbbandos/ofxstatement-be-ing
I've tested the plugin generating files that can be imported into kmymoney with more data than the import kmymoney does from CVS.

**Comment by jbbandos** [comment]
Forgot to add, feel free to add it to the plugins list.

**Comment by kedder** [comment]
Would you like to submit your changes as a pull request to @TheoMarescaux? Or would you rather take over maintenance of this plugin?

**Comment by jbbandos** [comment]
I have submitted them as a pull request, but it seems that @TheoMarescaux is awol? I see no changes on his repository for some time, and no answers to issues and pull requests.
Maybe it is better if I take over it, at least until Theo returns.

**Comment by TheoMarescaux** [comment]
Hi folks, I don't have time to follow this up. Feel free to support it.
Many thanks, Theo

**Comment by jbbandos** [comment]
Thanks Theo. How is it better to go forward with this, @kedder ?

**Comment by kedder** [comment]
@jbbandos sounds good. I'll link to your project as soon as I get home. Thanks!
