### ISSUE TITLE
new plugin: widiba and webank italian banks

### ISSUE THREAD

**Issue by ecorini** [kedder/ofxstatement#87]
Hi i added a plugin for widiba and webank italian banks: https://github.com/ecorini/ofxstatement-it-banks

**Comment by zeldigas** [comment]
@ecorini just create PR that adds your plugin to readme. It's as simple as https://github.com/kedder/ofxstatement/pull/112

**Comment by kedder** [comment]
I missed this issue completely. Going to add it to the readme. Sorry for slight delay, @ecorini.
