### ISSUE TITLE
release 0.6.2?

### ISSUE THREAD

**Issue by medovina** [kedder/ofxstatement#93]
Release 0.6.1 was in May 2017, over 2-1/2 years ago.  There have been some signfiicant and useful changes since that time, so could you possibly make a new release?

**Comment by kedder** [comment]
Good idea! Even though not much is happening in ofxstatement itself (most of stuff goes into plugins), it is worth releasing what we have accumulated so far.

ofxstatemnt-0.6.2 is on pypi.

**Comment by medovina** [comment]
Great - thanks for the quick reaction!
