### ISSUE TITLE
New plugins for Trust Merchant Bank (DRC) and Stanbic Bank (Zambia)

### ISSUE THREAD

**Issue by BIZ4Africa** [kedder/ofxstatement#97]
Trust Merchant Bank (DRC) : https://github.com/BIZ4Africa/ofxstatement-cd-tmb
Stanbic Bank (Zambia): https://github.com/BIZ4Africa/ofxstatement-zm-stanbic

**Comment by kedder** [comment]
Included in README, thanks @BIZ4Africa!
